### PR TITLE
Include URL to ptn.ninja in the reply to improve user experience

### PR DESCRIPTION
**Pull request by nitzel**
## Goal
Include a link to ptn.ninja with the the fully annotated PTN so that users can just click it to view the result.

## Motiviation
Downloading the resulting PTN file from discord and uploading it to ptn.ninja is an unnecessary chore to the users.

Since ptn.ninja URLs are usually too long for standard discord messages this PR uses the `url.ptn.ninja/short` URL Shortener service.

### CODE REVIEW

**Comment by nitzel** [comment]
I didn't have a discord bot token ready to verify the markdown is displayed correctly but the ptn.ninja URL generation and URL shortening were working fine when testing with `println!` in the `main` function.

**Comment by nitzel** [comment]
@MortenLohne ptn.ninja url shortener service is live, I've updated the code to use it :-) 

**edit**: nevermind, the returned URLs are currently `https://ptn.ninja/s/aYmVaDpoaxTUMqN50mWE` but only `https://next.ptn.ninja/s/aYmVaDpoaxTUMqN50mWE` is currently working (i.e. we would have to insert the sub-domain `next` into the returend URL).

We'll need to wait until Gruppler updates production for the URLs to work...

**Comment by gruppler** [comment]
The update with url shortener support has been deployed. The shortener now uses a hash of the parameters as the unique ID, so duplicate requests will return the same URL.

**Comment by nitzel** [comment]
@MortenLohne I guess this is ready for testing and merging then?

**Comment by MortenLohne** [comment]
Works perfectly, thanks!

**Pull request merged**
